### ISSUE TITLE
WK2 web process segfault when opening related pages

### ISSUE THREAD

**Issue by aidanholm** [aidanholm/luakit#170]
Following a link that opens a new tab will occasionally cause both current and new tabs to crash: caused by WebKit bug.

Platform: Arch x86_64 with kernel 4.9.6
Possibly only occurs with Intel graphics
```
#0  0x00007fa07f381da5 in __memmove_sse2_unaligned_erms () at /usr/lib/libc.so.6
#1  0x00007fa01aa8386f in  () at /usr/lib/xorg/modules/dri/i965_dri.so
#2  0x00007fa01aa8412a in  () at /usr/lib/xorg/modules/dri/i965_dri.so
#3  0x00007fa01aa846d6 in  () at /usr/lib/xorg/modules/dri/i965_dri.so
#4  0x00007fa01aaa0629 in  () at /usr/lib/xorg/modules/dri/i965_dri.so
#5  0x00007fa01aa82aa9 in  () at /usr/lib/xorg/modules/dri/i965_dri.so
#6  0x00007fa01a85808a in  () at /usr/lib/xorg/modules/dri/i965_dri.so
#7  0x00007fa080e3f5a7 in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#8  0x00007fa080df7fff in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#9  0x00007fa07fe86158 in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#10 0x00007fa07fe8edd7 in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#11 0x00007fa07fe8c6f5 in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#12 0x00007fa07cc01e05 in WTF::RunLoop::performWork() () at /usr/lib/libjavascriptcoregtk-4.0.so.18
#13 0x00007fa07cc38129 in  () at /usr/lib/libjavascriptcoregtk-4.0.so.18
#14 0x00007fa07d07643a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#15 0x00007fa07d0767f0 in  () at /usr/lib/libglib-2.0.so.0
#16 0x00007fa07d076b12 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#17 0x00007fa07cc38a30 in WTF::RunLoop::run() () at /usr/lib/libjavascriptcoregtk-4.0.so.18
#18 0x00007fa07cc3766e in  () at /usr/lib/libjavascriptcoregtk-4.0.so.18
#19 0x00007fa07cc02e15 in  () at /usr/lib/libjavascriptcoregtk-4.0.so.18
#20 0x00007fa07cc35b8a in  () at /usr/lib/libjavascriptcoregtk-4.0.so.18
#21 0x00007fa07b889454 in start_thread () at /usr/lib/libpthread.so.0
#22 0x00007fa07f3e67df in clone () at /usr/lib/libc.so.6
```

Workaround: downgrade webkit2gtk to 2.14.2-2

**Comment by aidanholm** [comment]
WebKit bug fixed in versions older than at least 2.14.5-1+
